// styles.ts
import { StyleSheet } from 'react-native';
import { wp, hp } from '../../../../utils/responsive';

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#000000',
  },
  bottomCard: {
    position: 'absolute',
    bottom: 0,
    width: '100%',
    backgroundColor: '#357EBD',
    borderTopLeftRadius: wp(5),
    borderTopRightRadius: wp(5),
    paddingHorizontal: wp(5),
    paddingTop: hp(1.5),
    alignItems: 'center',
    overflow: 'hidden',
    shadowColor: '#000',
    shadowOpacity: 0.3,
    shadowOffset: { width: 0, height: -4 },
    shadowRadius: 10,
    elevation: 10,
  },
  chevron: {
    alignSelf: 'center',
    marginBottom: hp(1),
  },
  headline: {
    fontSize: wp(5),
    fontWeight: 'bold',
    color: '#fff',
    marginBottom: hp(1),
    textAlign: 'center',
  },
  avatar: {
    width: wp(22),
    height: wp(22),
    borderRadius: wp(11),
    marginBottom: hp(1),
    borderWidth: 2,
    borderColor: '#fff',
  },
  name: {
    fontSize: wp(5),
    fontWeight: 'bold',
    color: '#fff',
    marginBottom: hp(0.7),
    textAlign: 'center',
  },
  ratingRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: hp(1),
  },
  rides: {
    color: '#fff',
    marginLeft: wp(1.5),
    fontSize: wp(3.5),
  },
  infoRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: hp(0.8),
  },
  infoText: {
    color: '#fff',
    fontSize: wp(4),
    marginHorizontal: wp(1),
    textAlign: 'center',
  },
  buttonRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: hp(2),
    marginBottom: hp(1),
    width: '100%',
    alignItems: 'center',
    paddingHorizontal: 0,
  },
  cancelButton: {
    flex: 1,
    flexDirection: 'row',
    backgroundColor: '#E74C3C',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: wp(7),
    paddingVertical: hp(1.5),
    marginRight: wp(2),
  },
  cancelText: {
    color: '#fff',
    fontWeight: 'bold',
    fontSize: wp(4.2),
  },
  messageButton: {
    flex: 1,
    flexDirection: 'row',
    backgroundColor: '#00C853',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: wp(7),
    paddingVertical: hp(1.5),
    marginLeft: wp(2),
    position: 'relative',
  },
  messageIcon: {
    marginRight: wp(2),
    alignSelf: 'center',
  },
  messageText: {
    color: '#fff',
    fontWeight: 'bold',
    fontSize: wp(4.2),
    marginRight: wp(1.5),
  },
  unreadBadge: {
    marginLeft: wp(2),
    backgroundColor: '#FF3B30',
    borderRadius: wp(3),
    minWidth: wp(5),
    paddingHorizontal: wp(1.5),
    paddingVertical: hp(0.3),
    alignItems: 'center',
    justifyContent: 'center',
  },
  unreadText: {
    color: '#fff',
    fontSize: wp(3.2),
    fontWeight: 'bold',
  },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#000000',
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.32)',
    alignItems: 'center',
    justifyContent: 'flex-end',
  },
  modalContainer: {
    width: '100%',
    padding: wp(7),
    backgroundColor: '#fff',
    borderTopLeftRadius: wp(5),
    borderTopRightRadius: wp(5),
    alignItems: 'center',
    shadowColor: '#333',
    shadowOpacity: 0.2,
    shadowOffset: { width: 0, height: -3 },
    shadowRadius: 12,
    elevation: 24,
  },
  modalTitle: {
    fontSize: wp(5.6),
    fontWeight: 'bold',
    marginBottom: hp(0.7),
    color: '#357EBD',
    textAlign: 'center',
  },
  modalSubtitle: {
    fontSize: wp(4.3),
    color: '#555',
    marginBottom: hp(2.2),
    textAlign: 'center',
  },
  modalPermanentButton: {
    width: '100%',
    backgroundColor: '#E74C3C',
    borderRadius: wp(3.5),
    paddingVertical: hp(1.5),
    marginBottom: hp(1.5),
    alignItems: 'center',
  },
  modalPermanentText: {
    color: '#fff',
    fontSize: wp(4.5),
    fontWeight: 'bold',
  },
  modalReopenButton: {
    width: '100%',
    backgroundColor: '#357EBD',
    borderRadius: wp(3.5),
    paddingVertical: hp(1.5),
    marginBottom: hp(1.5),
    alignItems: 'center',
  },
  modalReopenText: {
    color: '#fff',
    fontSize: wp(4.5),
    fontWeight: 'bold',
  },
  modalClose: {
    position: 'absolute',
    right: wp(3.7),
    top: wp(3.7),
    padding: wp(1.6),
  },
});
