import { StyleSheet } from 'react-native';
import { wp, hp } from '../../../../utils/responsive';

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#F7F9FC',
  },
  map: {
    width: wp(1),
    height: '100%',
  },
  markerLabel: {
    backgroundColor: '#fff',
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 6,
    borderColor: '#357EBD',
    borderWidth: 1,
    minWidth: 75,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOpacity: 0.1,
    shadowRadius: 4,
    shadowOffset: { width: 0, height: 2 },
    elevation: 3,
  },
  markerText: {
    fontSize: wp(3.6),
    fontWeight: '600',
    color: '#357EBD',
  },
  detailsPanel: {
    position: 'absolute',
    bottom: 0,
    width: '100%',
    backgroundColor: '#ffffff',
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    overflow: 'hidden',
    elevation: 20,
    shadowColor: '#000',
    shadowOpacity: 0.1,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: -4 },
  },
  arrowContainer: {
    backgroundColor: '#357EBD',
    height: 40,
    justifyContent: 'center',
    alignItems: 'center',
  },
  detailsContent: {
    paddingHorizontal: wp(5),
    paddingBottom: hp(15),
    paddingTop: hp(1),
  },
  row: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginVertical: hp(1.2),
    borderBottomWidth: 1,
    borderBottomColor: '#E0E0E0',
    paddingBottom: hp(1),
  },
  label: {
    flex: 0.45,
    fontSize: wp(4.2),
    color: '#333',
    fontWeight: '600',
  },
  value: {
    flex: 0.55,
    fontSize: wp(4.2),
    color: '#444',
    textAlign: 'right',
    fontWeight: '500',
  },
  price_value: {
    flex: 0.55,
    fontSize: wp(4.4),
    fontWeight: '700',
    color: '#1E88E5',
    textAlign: 'right',
  },
  messageButton: {
    backgroundColor: '#1E88E5',
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    paddingVertical: hp(2.5),
    marginHorizontal: wp(5),
    marginBottom: hp(1.5),
    borderRadius: 10,
    shadowColor: '#1E88E5',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 6,
    elevation: 4,
  },
  messageButtonText: {
    color: '#fff',
    fontSize: wp(4.2),
    fontWeight: '600',
    marginLeft: wp(2),
  },
  unreadBadge: {
    marginLeft: wp(2),
    backgroundColor: '#FF3B30',
    borderRadius: 12,
    minWidth: 24,
    paddingHorizontal: 6,
    paddingVertical: 2,
    alignItems: 'center',
    justifyContent: 'center',
  },
  unreadText: {
    color: '#fff',
    fontSize: wp(3.5),
    fontWeight: '700',
  },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: hp(2),
    backgroundColor: '#fff',
  },
  loadingText: {
    marginTop: hp(1),
    fontSize: wp(4),
    color: '#666',
    textAlign: 'center',
  },
  errorContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: hp(2),
    backgroundColor: '#fff',
  },
  errorText: {
    fontSize: wp(4.2),
    color: '#D32F2F',
    textAlign: 'center',
    fontWeight: '600',
  },
  goBackButton: {
    marginTop: hp(2),
    paddingHorizontal: wp(6),
    paddingVertical: hp(1.6),
    backgroundColor: '#D32F2F',
    borderRadius: 10,
  },
  goBackText: {
    color: '#fff',
    fontWeight: '600',
    fontSize: wp(4.2),
  },
  actionRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginHorizontal: wp(5),
    marginBottom: hp(3),
    gap: wp(3), // add if you want gap between buttons (optional, works on RN 0.71+)
  },
  actionButton: {
    flex: 1,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    paddingVertical: hp(2.5),
    borderRadius: 10,
  },
  cancelButton: {
    backgroundColor: '#D32F2F',
    marginRight: wp(2),
  },
  cancelButtonText: {
    color: '#fff',
    fontWeight: '700',
    fontSize: wp(4.2),
    marginLeft: wp(1.5),
  },
  completeButton: {
    backgroundColor: '#28A745',
    marginLeft: wp(2),
  },
  completeButtonText: {
    color: '#fff',
    fontWeight: '700',
    fontSize: wp(4.2),
    marginLeft: wp(1.5),
  },

});
